package node;

public enum NodeType {
    ASSIGNMENT,
    BLOCK,
    CONDITION,
    EVENT,
    EXPRESSION,
    FUNCTION,
    IF_STATEMENT,
    INT_LITERAL,
    REPEAT_IF_STATEMENT,
    REPEAT_STATEMENT,
    STRING_LITERAL,
    VARIABLE
}
